### ISSUE TITLE
Stacked bar chart

### ISSUE THREAD

**Issue by vinnytheviking** [jettro/c3-angular-sample#17]
Hi.

I'm wondering if you could help. Is there an easy way to implement stacked bar charts ?

From what I can see it's only the groups item that's missing. I tried adding it to the $scope but couldn't find where the you map from the dom into the scope.

Not having stacked bar charts is a show stopper for using your great directive.

thanks

Vinny

**Comment by jettro** [comment]
Don't know if you are in a real hurry. I have some open pull requests, but
I am incredibly busy for still a week. Can look into it, after that.

sorry

regards Jettro

On Wed, Mar 18, 2015 at 10:46 PM, vinnytheviking <notifications@github.com>
wrote:

> Hi.
>
> I'm wondering if you could help. Is there an easy way to implement stacked
> bar charts ?
>
> From what I can see it's only the groups item that's missing. I tried
> adding it to the $scope but couldn't find where the you map from the dom
> into the scope.
>
> Not having stacked bar charts is a show stopper for using your great
> directive.
>
> thanks
>
> Vinny
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jettro/c3-angular-sample/issues/17>.
>



-- 
Jettro Coenradie
http://www.gridshore.nl

**Comment by vinnytheviking** [comment]
thanks for getting back Jettro. I'm happy to wait a week or so. Much appreciated. Vinny

**Comment by jettro** [comment]
Sorry it took me a bit longer. Was very busy with some other things. Now the stacked bar chart is available. Check sample directive3.html for an example.

**Comment by vinnytheviking** [comment]
Thanks jettro

Much appreciated

Vinny

-----Original Message-----

**Comment by brandonros** [comment]
What about a regular bar chart? Why are there no examples for that?
